### ISSUE TITLE
Is it possible to get the marker information in the binary code?

### ISSUE THREAD

**Issue by Hanseltu** [abenkhadra/bcov#5]
Hi,

Thanks for your nice tool! May I ask something about CFG reported by `bcov`?

In my current work, I have inserted some `marker functions` to every block in the source code and then I compiled it to binary. I was expecting in CFG produced by `bcov` could see some `markers` in the `dot` file but not. So, is it possible to do so?

For example, consider the following simple experiment:
```
$objdump -S test1 | grep marker
(I only present some of them)
411405:	e8 28 1a ff ff       	callq  402e32 <marker_98>
  411432:	e8 3a 1a ff ff       	callq  402e71 <marker_101>
  411696:	e8 44 18 ff ff       	callq  402edf <marker_106>
  411753:	e8 f5 17 ff ff       	callq  402f4d <marker_111>
  41179f:	e8 01 18 ff ff       	callq  402fa5 <marker_115>
  4119cc:	e8 b4 b4 ff ff       	callq  40ce85 <marker_99999>
  411a42:	e8 f8 15 ff ff       	callq  40303f <marker_122>
  411c5d:	e8 e5 14 ff ff       	callq  403147 <marker_134>
  411ca3:	e8 f2 b1 ff ff       	callq  40ce9a <marker_88888>
  411cb9:	e8 e1 14 ff ff       	callq  40319f <marker_138>
  411e50:	e8 26 14 ff ff       	callq  40327b <marker_148>
  411e85:	e8 49 14 ff ff       	callq  4032d3 <marker_152>
  412139:	e8 17 13 ff ff       	callq  403455 <marker_170>
  412197:	e8 13 ad ff ff       	callq  40ceaf <marker_start>
  41252c:	e8 93 a9 ff ff       	callq  40cec4 <marker_end>
```
But in the `dot` file generated by `bcov`, none of the `marker functions` are presented.
```
$bcov -m dump -f "main" -i ./test1
$cat func_412181.cfg.dot | grep marker
(nothing)
```

Here is the binary I used:
[test1.zip](https://github.com/abenkhadra/bcov/files/8814570/test1.zip)

So, is it possible to make those makers be shown in the `dot` file under the current design of `bcov`? Or did I miss anything here? (I realized that `bcov` only reports markers in `main` function but ignores ones in the body of the function call, e.g., `func_1` in this case. Is possible to build the whole CFG that includes the body of the function calls?)

Thank you so much for your time and looking forward to your reply!

Best regards,
Haoxin

**Comment by abenkhadra** [comment]
Thanks for giving `bcov` a try.

`bcov` dumps function addresses instead of function names. So for example, you will find the address `40319f` but not its corresponding function name `marker_138`. 

A quick workaround would be to symbolize function names in the dot file. You can do something like,

```sh
sed -i 's/40319f/marker_138/' func_412181.cfg.dot
```

**Comment by Hanseltu** [comment]
Hi @abenkhadra, thanks for the quick response!

May I ask is it possible to get the whole CFG which includes the call relationship between the functions? For example, `marker_138` is not directly in the function `main` and it was called in another function (`func_14`), which was called by a function (`func_1`) inside the `main` function. So, there is no function address of `marker_138` in `func_412181.cfg.dot`.

Therefore, can I directly get the whole CFG using `bcov`? If not, I may manually construct it by combing the `dot` file of different functions. Or any other suggestions to build the CFG?

Thanks for your time again!

**Comment by abenkhadra** [comment]
I think you mean dumping the callgraph. Yes, `bcov` can dump the callgraph, but this functionality is not exposed to the user. It is not difficult to modify the source code to support that. 

The call graph is stored [here](https://github.com/abenkhadra/bcov/blob/master/src/elf/ElfModule.cpp#L427). It gets populated [here](https://github.com/abenkhadra/bcov/blob/master/src/elf/ElfModule.cpp#L1188). You can dump it simply by calling this [function](https://github.com/abenkhadra/bcov/blob/master/src/elf/ElfModule.cpp#L1728).
